# Generated by Django 4.1.5 on 2023-02-15 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='webdata',
            name='description',
        ),
    ]
